# Generated by Django 4.2.30 on 2026-09-02 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to=settings.AUTH_USER_MODEL),
        ),
    ]
