# Generated by Django 4.2.30 on 2026-09-15 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='usuario.usuario'),
        ),
    ]
