# Generated by Django 6.0.3 on 2026-09-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('dataInicio', models.CharField(max_length=20)),
                ('protocolo', models.CharField(max_length=100)),
                ('DataRenovacao', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Usuário da Troca',
                'verbose_name_plural': 'Usuários das Trocas',
            },
        ),
    ]
