# Generated by Django 4.2.29 on 2026-08-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trocas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('dataInicio', models.CharField(max_length=20)),
                ('protocolo', models.CharField(max_length=100)),
                ('DataRenovacao', models.CharField(blank=True, max_length=20, null=True)),
                ('troca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocas.troca')),
            ],
            options={
                'verbose_name': 'Usuário da Troca',
                'verbose_name_plural': 'Usuários das Trocas',
            },
        ),
    ]
