# Generated by Django 6.0.3 on 2026-09-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsuarioTroca', '0001_initial'),
        ('trocas', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotroca',
            name='troca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocas.troca'),
        ),
        migrations.AddField(
            model_name='usuariotroca',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
