# Generated by Django 4.2.30 on 2026-09-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('data_troca', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('ofertantes', models.CharField(max_length=100)),
                ('data_inicial', models.DateField()),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('interessado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('protocolo', models.CharField(max_length=50)),
                ('data_renovacao', models.DateField(blank=True, null=True)),
                ('troca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocas.troca')),
            ],
        ),
    ]
