# Generated by Django 4.2.30 on 2026-09-01 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('data_troca', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.objeto')),
            ],
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('ofertantes', models.CharField(max_length=100)),
                ('data_inicial', models.DateField()),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('interessado', models.CharField(max_length=100)),
                ('objetos', models.ManyToManyField(related_name='trocas', through='trocas.ObjetoTroca', to='objetos.objeto')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('protocolo', models.CharField(max_length=50)),
                ('data_renovacao', models.DateField(blank=True, null=True)),
                ('troca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocas.troca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_usuario_trocas', to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='troca',
            name='usuarios',
            field=models.ManyToManyField(related_name='trocas', through='trocas.UsuarioTroca', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='objetotroca',
            name='troca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocas.troca'),
        ),
    ]
