# Generated by Django 4.2.30 on 2026-09-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('UsuarioTroca', '0003_initial'),
        ('trocas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='troca',
            name='usuarios',
            field=models.ManyToManyField(related_name='trocas', through='UsuarioTroca.UsuarioTroca', to='usuario.usuario'),
        ),
    ]
