# Generated by Django 4.2.30 on 2026-09-02 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trocas', '0001_initial'),
        ('objetos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotroca',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_usuario_trocas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='troca',
            name='objetos',
            field=models.ManyToManyField(related_name='trocas', through='trocas.ObjetoTroca', to='objetos.objeto'),
        ),
        migrations.AddField(
            model_name='troca',
            name='usuarios',
            field=models.ManyToManyField(related_name='trocas', through='trocas.UsuarioTroca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetotroca',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.objeto'),
        ),
        migrations.AddField(
            model_name='objetotroca',
            name='troca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocas.troca'),
        ),
    ]
