# Generated by Django 4.2.29 on 2026-08-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('data_troca', models.CharField(max_length=20)),
                ('obsevação', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Objeto da Troca',
                'verbose_name_plural': 'Objetos das Trocas',
            },
        ),
    ]
