# Generated by Django 6.0.3 on 2026-09-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoTroca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('data_troca', models.CharField(max_length=20)),
                ('obsevação', models.TextField(blank=True, null=True)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.objeto')),
            ],
            options={
                'verbose_name': 'Objeto da Troca',
                'verbose_name_plural': 'Objetos das Trocas',
            },
        ),
    ]
