# Generated by Django 4.2.30 on 2026-09-15 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetos', '0001_initial'),
        ('ObjetoTroca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetotroca',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.objeto'),
        ),
    ]
