# Generated by Django 4.2.29 on 2026-08-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trocas', '0001_initial'),
        ('objetos', '0001_initial'),
        ('ObjetoTroca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetotroca',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos.objeto'),
        ),
        migrations.AddField(
            model_name='objetotroca',
            name='troca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocas.troca'),
        ),
    ]
